[package]
name = "lipl-display-xilem"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
json-lines = { path = "../json-lines" }
lipl-display-common = "0.4.6"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
xilem = "0.4.0"
